# Generated by Django 5.0 on 2023-12-30 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('big_auto_field', models.BigAutoField(primary_key=True, serialize=False)),
                ('email_field', models.EmailField(max_length=254)),
                ('char_field', models.CharField(max_length=255)),
                ('text_field', models.TextField()),
                ('binary_field', models.BinaryField()),
                ('boolean_field', models.BooleanField()),
                ('date_field', models.DateField()),
                ('date_time_field', models.DateTimeField()),
                ('decimal_field', models.DecimalField(decimal_places=2, max_digits=5)),
                ('duration_field', models.DurationField()),
                ('integer_field', models.IntegerField()),
                ('float_field', models.FloatField()),
                ('time_field', models.TimeField()),
            ],
        ),
    ]
