# Generated by Django 5.0 on 2023-12-30 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_fields_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='date_time_field',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='duration_field',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='time_field',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
