# Generated by Django 5.0 on 2023-12-30 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_fields_app', '0002_alter_mymodel_date_time_field_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mymodel',
            name='date_field',
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='date_time_field',
            field=models.DateTimeField(null=True),
        ),
    ]
