# Generated by Django 5.0 on 2023-12-30 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_fields_app', '0003_remove_mymodel_date_field_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='date_time_field',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
