# Generated by Django 5.0.1 on 2024-01-10 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musician', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='musician',
            old_name='instrment_type',
            new_name='instrument_type',
        ),
    ]
